### ISSUE TITLE
Default to [] for No Matches in Query Results

### ISSUE THREAD

**Issue by fasblom** [webmaxru/node-red-contrib-neo4j-bolt#10]
Currently, the module does not return anything when a query yields no matches. For consistency and to simplify downstream processing in Node-RED flows, it would be good if possible if the module could return an empty array ([]) instead.

**Comment by fasblom** [comment]
Fix available in PR #11

**Comment by webmaxru** [comment]
Thank you for your next contribution, @fasblom !
I published 2.5.2
