### ISSUE TITLE
msg.database not picked up when calling Neo4j

### ISSUE THREAD

**Issue by fasblom** [webmaxru/node-red-contrib-neo4j-bolt#7]
It seems like `msg.database` is not being used when calling Neo4j. The database used is either the one set in the config node, if none is set it defaults to `neo4j`.

This behavior seems to be related to the logic in the [neo4j.js](https://github.com/webmaxru/node-red-contrib-neo4j-bolt/blob/master/neo4j.js) file.

**Comment by webmaxru** [comment]
Hello @bonnydeal!
Could you have a look? Could it be related with your latest feature added?

**Comment by fasblom** [comment]
@webmaxru - I've submitted PR #8 that fixes the issue

**Comment by webmaxru** [comment]
Thank you!
I published updated version 2.5.1
